- hosts: saturn
  become: true
  gather_facts: true
  roles:
    - hypha.common.provision_ssh_keys
    - hypha.common.harden_ssh
    - hypha.common.setup
    - hypha.common.unattended_upgrades
    - geerlingguy.docker
    - hypha.common.firewall
    - saturn_l1
    - hypha.common.node_exporter
    - hypha.common.prometheus_exporter_addnode
    - hypha.common.prometheus_exporter_docker
    - hypha.common.promtail
