---

### Enable LOKI Logger Driver and settings
- name: Install LOKI Driver
  shell: "docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions"
  when: browsertrix_loki is defined
  ignore_errors: true

- name: Enable LOKI Docker Driver
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Create storage directory
  file:
    path: /mnt/data
    state: directory
    owner: root
    group: root

- name: Create saturn home directory
  file:
    path: /mnt/data/saturn
    state: directory
    owner: root
    group: root

- name: Download run command
  get_url:
    force: true
    url: "https://raw.githubusercontent.com/filecoin-saturn/L1-node/main/run.sh"
    dest: /mnt/data/saturn/run.sh
    mode: 0777

- name: Ddownload update command
  get_url:
    force: true
    url: "https://raw.githubusercontent.com/filecoin-saturn/L1-node/main/update.sh"
    dest: /mnt/data/saturn/update.sh
    mode: 0777

- name: Provision config
  template:
    src: init.sh
    dest: /mnt/data/saturn/init.sh
    mode: 0777
    
- name: Ensure update happens every 5 mins
  ansible.builtin.cron:
    name: "update"
    minute: "*/5"
    job: "/mnt/data/saturn/init.sh update.sh >> /mnt/data/saturn/l1-cron.log 2>&1"

- name: Run docker
  ansible.builtin.shell: ./init.sh run.sh
  args:
    chdir: /mnt/data/saturn/

- name: Update docker
  ansible.builtin.shell: ./init.sh update.sh
  args:
    chdir: /mnt/data/saturn/
