---
- name: Create saturn-l1 directory
  file:
    path: /opt/saturn-l1
    state: directory
    owner: root
    group: root

- name: Create storage directory
  file:
    path: /mnt/md0
    state: directory
    owner: root
    group: root

- name: Create saturn storagedirectory
  file:
    path: /mnt/md0/saturn
    state: directory
    owner: root
    group: root

- name: download run command
  get_url:
    force: true
    url: "https://raw.githubusercontent.com/filecoin-saturn/L1-node/main/run.sh"
    dest: /opt/saturn-l1/run.sh
    mode: 0777

- name: download update  command
  get_url:
    force: true
    url: "https://raw.githubusercontent.com/filecoin-saturn/L1-node/main/update.sh"
    dest: /opt/saturn-l1/update.sh
    mode: 0777

- name: provision config
  template:
    src: init.sh
    dest: /opt/saturn-l1/init.sh
    mode: 0777
    
- name: Ensure update happens every 5 mins
  ansible.builtin.cron:
    name: "update"
    minute: "*/5"
    job: "/opt/saturn-l1/init.sh update.sh >> /opt/saturn-l1/l1-cron.log"

- name: Run docker
  ansible.builtin.shell: ./init.sh run.sh
  args:
    chdir: /opt/saturn-l1/

- name: Update docker
  ansible.builtin.shell: ./init.sh update.sh
  args:
    chdir: /opt/saturn-l1/
