#!/bin/bash
export FIL_WALLET_ADDRESS="{{ SATURN_FILECOIN_ADDRESS }}"
export NODE_OPERATOR_EMAIL="{{ SATURN_EMAIL }}"
export SATURN_NETWORK="{{ SATURN_NETWORK }}"
export SATURN_HOME=/mnt/md0/saturn
./$1